# HW6Task3

In [1]:
import numpy as np

In [2]:
def f(x):
    return np.array([x[0]**2 - 2 * x[1]**4 + 1, x[0] - x[1]**3 + 1])
def der(x):
    return np.array([[2 * x[0], -8 * x[1]**3],
                   [1, -3 * x[1]**2]])

In [3]:
def iteration(f, der, x0):
    return x0 - np.linalg.inv(der(x0)) @ f(x0)

In [4]:
#найдём решение на единичном круге
x = [[0, 1]]
for i in range(20):
    x += [iteration(f, der, x[-1])]

In [5]:
x

[[0, 1],
 array([-0.375,  0.875]),
 array([-0.35129856,  0.86576117]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596]),
 array([-0.35119943,  0.86570596])]

In [6]:
#проверим наше решение

In [7]:
from scipy.optimize import newton_krylov

In [8]:
x0 = np.array([0, 1])
newton_krylov(f, x0)

array([-0.35119943,  0.86570596])